
package ru._1c.ssl.exchange_2_0_1_6;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ru._1c.v8._8_1.data.core.Structure;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Exchange_2_0_1_6PortType", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
@XmlSeeAlso({
    ru._1c.v8._8_1.data.core.ObjectFactory.class,
    ru._1c.ssl.exchange_2_0_1_6.ObjectFactory.class
})
public interface Exchange2016PortType {


    /**
     * 
     * @param data
     * @param nodeCode
     * @param exchangePlanName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Upload", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:Upload")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "Upload", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.Upload")
    @ResponseWrapper(localName = "UploadResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.UploadResponse")
    public String upload(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName,
        @WebParam(name = "NodeCode", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String nodeCode,
        @WebParam(name = "Data", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.OUT)
        Holder<byte[]> data);

    /**
     * 
     * @param data
     * @param nodeCode
     * @param exchangePlanName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Download", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:Download")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "Download", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.Download")
    @ResponseWrapper(localName = "DownloadResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.DownloadResponse")
    public String download(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName,
        @WebParam(name = "NodeCode", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String nodeCode,
        @WebParam(name = "Data", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        byte[] data);

    /**
     * 
     * @param continuousOperationAllowed
     * @param nodeCode
     * @param continuousOperation
     * @param exchangePlanName
     * @param operation
     * @param fileID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadData", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:UploadData")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "UploadData", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.UploadData")
    @ResponseWrapper(localName = "UploadDataResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.UploadDataResponse")
    public String uploadData(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName,
        @WebParam(name = "NodeCode", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String nodeCode,
        @WebParam(name = "FileID", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.INOUT)
        Holder<String> fileID,
        @WebParam(name = "ContinuousOperation", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.INOUT)
        Holder<Boolean> continuousOperation,
        @WebParam(name = "Operation", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.INOUT)
        Holder<String> operation,
        @WebParam(name = "ContinuousOperationAllowed", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        boolean continuousOperationAllowed);

    /**
     * 
     * @param continuousOperationAllowed
     * @param nodeCode
     * @param continuousOperation
     * @param exchangePlanName
     * @param operation
     * @param fileID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DownloadData", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:DownloadData")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "DownloadData", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.DownloadData")
    @ResponseWrapper(localName = "DownloadDataResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.DownloadDataResponse")
    public String downloadData(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName,
        @WebParam(name = "NodeCode", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String nodeCode,
        @WebParam(name = "FileID", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String fileID,
        @WebParam(name = "ContinuousOperation", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.INOUT)
        Holder<Boolean> continuousOperation,
        @WebParam(name = "Operation", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.INOUT)
        Holder<String> operation,
        @WebParam(name = "ContinuousOperationAllowed", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        boolean continuousOperationAllowed);

    /**
     * 
     * @param nodeCode
     * @param exchangePlanName
     * @param resultMessage
     * @return
     *     returns ru._1c.v8._8_1.data.core.Structure
     */
    @WebMethod(operationName = "GetIBParameters", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:GetIBParameters")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "GetIBParameters", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetIBParameters")
    @ResponseWrapper(localName = "GetIBParametersResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetIBParametersResponse")
    public Structure getIBParameters(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName,
        @WebParam(name = "NodeCode", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String nodeCode,
        @WebParam(name = "ResultMessage", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.INOUT)
        Holder<String> resultMessage);

    /**
     * 
     * @param tableName
     * @return
     *     returns ru._1c.v8._8_1.data.core.Structure
     */
    @WebMethod(operationName = "GetIBData", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:GetIBData")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "GetIBData", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetIBData")
    @ResponseWrapper(localName = "GetIBDataResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetIBDataResponse")
    public Structure getIBData(
        @WebParam(name = "TableName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String tableName);

    /**
     * 
     * @param exchangePlanName
     * @return
     *     returns ru._1c.v8._8_1.data.core.Structure
     */
    @WebMethod(operationName = "GetCommonNodsData", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:GetCommonNodsData")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "GetCommonNodsData", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetCommonNodsData")
    @ResponseWrapper(localName = "GetCommonNodsDataResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetCommonNodsDataResponse")
    public Structure getCommonNodsData(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName);

    /**
     * 
     * @param filterSettings
     * @param exchangePlanName
     * @param additionalSettings
     * @param parameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateExchange", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:CreateExchange")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "CreateExchange", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.CreateExchange")
    @ResponseWrapper(localName = "CreateExchangeResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.CreateExchangeResponse")
    public String createExchange(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName,
        @WebParam(name = "Parameters", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String parameters,
        @WebParam(name = "FilterSettings", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        Structure filterSettings,
        @WebParam(name = "AdditionalSettings", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        Structure additionalSettings);

    /**
     * 
     * @param nodeCode
     * @param exchangePlanName
     * @param additionalSettings
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateExchange", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:UpdateExchange")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "UpdateExchange", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.UpdateExchange")
    @ResponseWrapper(localName = "UpdateExchangeResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.UpdateExchangeResponse")
    public String updateExchange(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName,
        @WebParam(name = "NodeCode", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String nodeCode,
        @WebParam(name = "AdditionalSettings", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        Structure additionalSettings);

    /**
     * 
     * @param nodeCode
     * @param continuousOperation
     * @param exchangePlanName
     * @param operation
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegisterOnlyCatalogData", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:RegisterOnlyCatalogData")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "RegisterOnlyCatalogData", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.RegisterOnlyCatalogData")
    @ResponseWrapper(localName = "RegisterOnlyCatalogDataResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.RegisterOnlyCatalogDataResponse")
    public String registerOnlyCatalogData(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName,
        @WebParam(name = "NodeCode", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String nodeCode,
        @WebParam(name = "ContinuousOperation", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.INOUT)
        Holder<Boolean> continuousOperation,
        @WebParam(name = "Operation", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.OUT)
        Holder<String> operation);

    /**
     * 
     * @param nodeCode
     * @param continuousOperation
     * @param exchangePlanName
     * @param operation
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegisterAllDataExceptCatalogs", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:RegisterAllDataExceptCatalogs")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "RegisterAllDataExceptCatalogs", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.RegisterAllDataExceptCatalogs")
    @ResponseWrapper(localName = "RegisterAllDataExceptCatalogsResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.RegisterAllDataExceptCatalogsResponse")
    public String registerAllDataExceptCatalogs(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName,
        @WebParam(name = "NodeCode", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String nodeCode,
        @WebParam(name = "ContinuousOperation", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.INOUT)
        Holder<Boolean> continuousOperation,
        @WebParam(name = "Operation", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.OUT)
        Holder<String> operation);

    /**
     * 
     * @param resultMessage
     * @param operation
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetContinuousOperationStatus", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:GetContinuousOperationStatus")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "GetContinuousOperationStatus", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetContinuousOperationStatus")
    @ResponseWrapper(localName = "GetContinuousOperationStatusResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetContinuousOperationStatusResponse")
    public String getContinuousOperationStatus(
        @WebParam(name = "Operation", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String operation,
        @WebParam(name = "ResultMessage", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.OUT)
        Holder<String> resultMessage);

    /**
     * 
     * @param name
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetFunctionalOption", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:GetFunctionalOption")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "GetFunctionalOption", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetFunctionalOption")
    @ResponseWrapper(localName = "GetFunctionalOptionResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetFunctionalOptionResponse")
    public boolean getFunctionalOption(
        @WebParam(name = "Name", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String name);

    /**
     * 
     * @param partQuantity
     * @param transferId
     * @param blockSize
     * @param fileId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PrepareGetFile", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:PrepareGetFile")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "PrepareGetFile", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.PrepareGetFile")
    @ResponseWrapper(localName = "PrepareGetFileResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.PrepareGetFileResponse")
    public String prepareGetFile(
        @WebParam(name = "FileId", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String fileId,
        @WebParam(name = "BlockSize", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        BigDecimal blockSize,
        @WebParam(name = "TransferId", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.OUT)
        Holder<String> transferId,
        @WebParam(name = "PartQuantity", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.OUT)
        Holder<Integer> partQuantity);

    /**
     * 
     * @param partData
     * @param partNumber
     * @param transferId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFilePart", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:GetFilePart")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "GetFilePart", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetFilePart")
    @ResponseWrapper(localName = "GetFilePartResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetFilePartResponse")
    public String getFilePart(
        @WebParam(name = "TransferId", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String transferId,
        @WebParam(name = "PartNumber", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        int partNumber,
        @WebParam(name = "PartData", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.OUT)
        Holder<byte[]> partData);

    /**
     * 
     * @param transferId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReleaseFile", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:ReleaseFile")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "ReleaseFile", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.ReleaseFile")
    @ResponseWrapper(localName = "ReleaseFileResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.ReleaseFileResponse")
    public String releaseFile(
        @WebParam(name = "TransferId", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String transferId);

    /**
     * 
     * @param partData
     * @param partNumber
     * @param transferId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PutFilePart", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:PutFilePart")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "PutFilePart", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.PutFilePart")
    @ResponseWrapper(localName = "PutFilePartResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.PutFilePartResponse")
    public String putFilePart(
        @WebParam(name = "TransferId", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String transferId,
        @WebParam(name = "PartNumber", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        Integer partNumber,
        @WebParam(name = "PartData", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        byte[] partData);

    /**
     * 
     * @param partQuantity
     * @param transferId
     * @param fileId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SaveFileFromParts", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:SaveFileFromParts")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "SaveFileFromParts", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.SaveFileFromParts")
    @ResponseWrapper(localName = "SaveFileFromPartsResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.SaveFileFromPartsResponse")
    public String saveFileFromParts(
        @WebParam(name = "TransferId", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String transferId,
        @WebParam(name = "PartQuantity", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        int partQuantity,
        @WebParam(name = "FileId", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.OUT)
        Holder<String> fileId);

    /**
     * 
     * @param fileName
     * @param fileId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PutFileIntoStorage", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:PutFileIntoStorage")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "PutFileIntoStorage", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.PutFileIntoStorage")
    @ResponseWrapper(localName = "PutFileIntoStorageResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.PutFileIntoStorageResponse")
    public String putFileIntoStorage(
        @WebParam(name = "FileName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String fileName,
        @WebParam(name = "FileId", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.OUT)
        Holder<String> fileId);

    /**
     * 
     * @param fileId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFileFromStorage", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:GetFileFromStorage")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "GetFileFromStorage", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetFileFromStorage")
    @ResponseWrapper(localName = "GetFileFromStorageResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.GetFileFromStorageResponse")
    public String getFileFromStorage(
        @WebParam(name = "FileId", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String fileId);

    /**
     * 
     * @param fileName
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "FileExists", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:FileExists")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "FileExists", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.FileExists")
    @ResponseWrapper(localName = "FileExistsResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.FileExistsResponse")
    public boolean fileExists(
        @WebParam(name = "FileName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String fileName);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Ping", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:Ping")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.PingResponse")
    public String ping();

    /**
     * 
     * @param result
     * @param nodeCode
     * @param exchangePlanName
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "TestConnection", action = "http://www.1c.ru/SSL/Exchange_2_0_1_6#Exchange_2_0_1_6:TestConnection")
    @WebResult(targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
    @RequestWrapper(localName = "TestConnection", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.TestConnection")
    @ResponseWrapper(localName = "TestConnectionResponse", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", className = "ru._1c.ssl.exchange_2_0_1_6.TestConnectionResponse")
    public boolean testConnection(
        @WebParam(name = "ExchangePlanName", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String exchangePlanName,
        @WebParam(name = "NodeCode", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6")
        String nodeCode,
        @WebParam(name = "Result", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", mode = WebParam.Mode.OUT)
        Holder<String> result);

}
