
package ru._1c.ssl.exchange_2_0_1_6;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Exchange_2_0_1_6", targetNamespace = "http://www.1c.ru/SSL/Exchange_2_0_1_6", wsdlLocation = "http://1c.stolplit.ru/HR/ws/exchange_2_0_1_6.1cws?wsdl")
public class Exchange2016
    extends Service
{

    private final static URL EXCHANGE2016_WSDL_LOCATION;
    private final static WebServiceException EXCHANGE2016_EXCEPTION;
    private final static QName EXCHANGE2016_QNAME = new QName("http://www.1c.ru/SSL/Exchange_2_0_1_6", "Exchange_2_0_1_6");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://1c.stolplit.ru/HR/ws/exchange_2_0_1_6.1cws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXCHANGE2016_WSDL_LOCATION = url;
        EXCHANGE2016_EXCEPTION = e;
    }

    public Exchange2016() {
        super(__getWsdlLocation(), EXCHANGE2016_QNAME);
    }

    public Exchange2016(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXCHANGE2016_QNAME, features);
    }

    public Exchange2016(URL wsdlLocation) {
        super(wsdlLocation, EXCHANGE2016_QNAME);
    }

    public Exchange2016(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXCHANGE2016_QNAME, features);
    }

    public Exchange2016(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Exchange2016(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Exchange2016PortType
     */
    @WebEndpoint(name = "Exchange_2_0_1_6Soap")
    public Exchange2016PortType getExchange2016Soap() {
        return super.getPort(new QName("http://www.1c.ru/SSL/Exchange_2_0_1_6", "Exchange_2_0_1_6Soap"), Exchange2016PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Exchange2016PortType
     */
    @WebEndpoint(name = "Exchange_2_0_1_6Soap")
    public Exchange2016PortType getExchange2016Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.1c.ru/SSL/Exchange_2_0_1_6", "Exchange_2_0_1_6Soap"), Exchange2016PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXCHANGE2016_EXCEPTION!= null) {
            throw EXCHANGE2016_EXCEPTION;
        }
        return EXCHANGE2016_WSDL_LOCATION;
    }

}
